#!/usr/bin/env python3
"""Build Use + Depletion cash-flow ledger for HYP-131 (zero-count until incremental)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "imports" / "arkansas-revenue-replacement"
OUT.mkdir(parents=True, exist_ok=True)

SLICE = "CC-ARKANSAS-PUBLIC-INCOME-ENGINE-USE-AND-DEPLETION-CASHFLOWS-1.0"
DEC, UPD = "CC-DEC-128", "UPD-141"
COMBINED_TARGET = 7_231_905_638

# Bound DFA figures
NG_FY2026 = 25_615_616
NG_FY2025 = 19_207_300
NG_FY2024 = 16_410_021
NG_FY2023 = 76_905_366
OIL_FY2026 = 12_176_540
OIL_FY2025 = 11_212_384
FUEL_FY2026 = 571_758_869.60  # excludes petroleum environmental fee
FUEL_CAL_2025_WITH_FEE = 560_473_542.51
MCF_CY2025 = 314_253_930
GR_SEVERANCE_FY2026 = 10_600_000  # DFA GR table line (subset)

# Statutory allocation (NCSL / AR practice)
NG_TO_GR_SHARE = 0.05
NG_TO_HIGHWAY_SHARE = 0.95


def candidate(**kwargs):
    required = [
        "id",
        "engine",
        "name",
        "income_form",
        "addressable_base",
        "current_rate_or_structure",
        "current_collections_usd",
        "already_spent",
        "already_spent_note",
        "legally_plausible_alternative",
        "gross_revenue_note",
        "collection_admin_cost",
        "behavioral_response",
        "local_community_share",
        "state_share",
        "volatility",
        "stress_case",
        "incremental_recurring_usd_countable",
        "constitutional_legal_status",
        "bucket",
        "proportionality_or_depletion_test",
    ]
    for r in required:
        if r not in kwargs:
            raise KeyError(r)
    return kwargs


def main() -> None:
    ng_gr_portion = round(NG_FY2026 * NG_TO_GR_SHARE)
    ng_hwy_portion = NG_FY2026 - ng_gr_portion
    # Illustrative market-value reverse engineer at assumed $3/Mcf (NOT a price bind)
    illustrative_mv_at_3 = MCF_CY2025 * 3.0
    illustrative_5pct = illustrative_mv_at_3 * 0.05
    # Blended effective rate from FY26 revenue / illustrative MV — sensitivity only
    blended_eff = NG_FY2026 / illustrative_mv_at_3 if illustrative_mv_at_3 else None

    use_candidates = [
        candidate(
            id="USE-MOTOR-FUEL",
            engine="USE",
            name="Motor fuel tax (gasoline/diesel + related)",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={
                "status": "BOUND",
                "fy2025_26_receipts_usd_ex_pet_env_fee": FUEL_FY2026,
                "calendar_2025_receipts_usd_incl_fee": FUEL_CAL_2025_WITH_FEE,
                "source": "DFA Motor Fuel Tax Section — Total Receipts by Fiscal Year; gclpefFY2024_2029",
            },
            current_rate_or_structure="Per-gallon motor fuel / distillate excise structure (Highway Revenue Distribution Law)",
            current_collections_usd=round(FUEL_FY2026),
            already_spent=True,
            already_spent_note="Special revenue for highways/transport — cannot double-count toward IIT/property Tax Retirement Fund",
            legally_plausible_alternative="Rate/index changes or heavy-vehicle differential require statute; EV road-use fee redesign possible but currently small and highway-tied",
            gross_revenue_note="~$572M FY2026 bound — material Use scale, already dedicated",
            collection_admin_cost="EXISTING_SYSTEM — low marginal admin",
            behavioral_response="Fuel efficiency / EV shift erodes gallons; demand somewhat inelastic short-run",
            local_community_share="Via Highway Revenue Distribution (cities/counties/state aid formulas)",
            state_share="Majority via AHTD / highway accounts",
            volatility="MODERATE — gallons stable vs severance; EV transition medium-run risk",
            stress_case="Deep recession or rapid EV adoption reduces gallons; fee redesign needed",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Generally applicable user excise; proportional to road use if gallons≈use (weakening with EVs)",
            bucket="NOT_MATERIAL_AS_REPLACEMENT_ENGINE",
            proportionality_or_depletion_test="Strong use-proportionality vs homeownership tax; fails replacement test because already spent and must stay with roads unless new incremental yield designed",
            sub_bucket_note="SUPPORT_ENGINE — keep for roads; do not raid for IIT replacement",
        ),
        candidate(
            id="USE-HEAVY-VEHICLE-IFTA",
            engine="USE",
            name="Heavy-vehicle / IFTA / interstate user charges",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={
                "status": "PARTIAL",
                "blr_ytd_may_fy2026_motor_fuel_interstate_users_usd": 14509014,
                "note": "BLR May FY2026 special revenue line; full ESAL/VMT freight base NEE",
            },
            current_rate_or_structure="IFTA / interstate motor fuel user charges; trip permits; related highway fees",
            current_collections_usd=14509014,
            already_spent=True,
            already_spent_note="Highway/transport special revenues",
            legally_plausible_alternative="Weight-distance / ESAL-based heavy truck fee would need statute + Commerce Clause-compliant design",
            gross_revenue_note="Bound interstate line is small vs fuel total; incremental headroom UNMODELED",
            collection_admin_cost="IFTA exists; new weight-distance would raise admin/compliance cost",
            behavioral_response="Route diversion / border shopping if non-harmonized",
            local_community_share="Highway distribution",
            state_share="Highway distribution",
            volatility="Freight-cycle sensitive",
            stress_case="Freight recession; trucking opposition; legal challenge if discriminatory",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Must be generally applicable / not unduly burden interstate commerce",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Best Use alignment (cost-imposed by heavy trucks) — needs ESAL model before any count",
        ),
        candidate(
            id="USE-EV-HYBRID-REG",
            engine="USE",
            name="Electric/hybrid vehicle registration fee",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={
                "status": "PARTIAL",
                "blr_ytd_may_fy2026_usd": 3982055,
                "note": "Road-use substitute as gallons erode",
            },
            current_rate_or_structure="Flat EV/hybrid registration fee (highway special revenue)",
            current_collections_usd=3982055,
            already_spent=True,
            already_spent_note="Highway/transport special revenues",
            legally_plausible_alternative="Mileage-based user fee pilots — legal/admin pending",
            gross_revenue_note="~$4M YTD — not material vs $7.23B",
            collection_admin_cost="Low (existing registration)",
            behavioral_response="Minor effect on EV adoption at current scale",
            local_community_share="Highway distribution",
            state_share="Highway distribution",
            volatility="Grows with EV fleet; still small",
            stress_case="Political pushback on EV fees",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Generally applicable registration fee",
            bucket="NOT_MATERIAL_AS_REPLACEMENT_ENGINE",
            proportionality_or_depletion_test="Philosophically aligned as gallons erode; scale negligible for replacement burden",
        ),
        candidate(
            id="USE-AIRPORT-AVIATION",
            engine="USE",
            name="Airport / aviation use charges",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={"status": "NEE", "note": "FAA/airport authority revenues not statewide-bound this slice"},
            current_rate_or_structure="PFC/landing/fuel flowage — largely federal/airport-enterprise constrained",
            current_collections_usd=None,
            already_spent=True,
            already_spent_note="Typically pledged to airport enterprise / federal PFC rules",
            legally_plausible_alternative="Limited state capture without conflicting federal airport grant assurances",
            gross_revenue_note="UNMODELED",
            collection_admin_cost="NEE",
            behavioral_response="Airline/route sensitivity",
            local_community_share="Airport sponsors",
            state_share="Limited",
            volatility="Travel-cycle",
            stress_case="Federal preemption / grant assurance conflicts",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Heavy federal overlay",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Use-aligned but likely not a state Tax Retirement Fund engine",
        ),
        candidate(
            id="USE-PORTS-INTERMODAL",
            engine="USE",
            name="Ports / intermodal facility use",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={"status": "NEE"},
            current_rate_or_structure="Local port authority tariffs / leases",
            current_collections_usd=None,
            already_spent=None,
            already_spent_note="Unknown without authority financials — treat as not free GR",
            legally_plausible_alternative="State participation / ground lease returns (overlaps Enterprise/Value Capture)",
            gross_revenue_note="UNMODELED",
            collection_admin_cost="NEE",
            behavioral_response="Modal diversion",
            local_community_share="Likely dominant",
            state_share="NEE",
            volatility="Trade/freight cycle",
            stress_case="Competition from out-of-state ports",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Local authority / lease law",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Use-aligned; scale unknown; better as Enterprise/External Income participation",
        ),
        candidate(
            id="USE-WATER-WASTE",
            engine="USE",
            name="Water / waste system use charges",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={"status": "NEE", "note": "Municipal enterprise funds dominate"},
            current_rate_or_structure="Local utility rates",
            current_collections_usd=None,
            already_spent=True,
            already_spent_note="Enterprise funds support system O&M/debt — not IIT replacement",
            legally_plausible_alternative="State industrial water withdrawal fee (see DEPLETION-WATER)",
            gross_revenue_note="Household water/waste rate hikes would recreate broad household burden — reject as IIT swap",
            collection_admin_cost="Local systems exist",
            behavioral_response="Conservation; affordability crisis if raised broadly",
            local_community_share="Local utilities",
            state_share="Low for retail water",
            volatility="Stable",
            stress_case="Regressive incidence if used as replacement tax",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Local utility ratemaking",
            bucket="NOT_MATERIAL_AS_REPLACEMENT_ENGINE",
            proportionality_or_depletion_test="FAILS replacement design if it taxes ordinary household existence-adjacent services",
        ),
        candidate(
            id="USE-SPECIALIZED-PERMITS",
            engine="USE",
            name="Specialized permitting / regulatory use fees",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={"status": "NEE"},
            current_rate_or_structure="Scattered agency fees",
            current_collections_usd=None,
            already_spent=True,
            already_spent_note="Usually cost-recovery for agencies",
            legally_plausible_alternative="Full-cost recovery where underpriced — incremental only after cost study",
            gross_revenue_note="Typically not material at statewide replacement scale",
            collection_admin_cost="Agency-specific",
            behavioral_response="Application volume changes",
            local_community_share="Varies",
            state_share="Varies",
            volatility="Low-moderate",
            stress_case="Fee-tax distinction litigation if punitive",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Fee must reasonably relate to service/cost",
            bucket="NOT_MATERIAL_AS_REPLACEMENT_ENGINE",
            proportionality_or_depletion_test="OK for cost recovery; not a $7B engine",
        ),
        candidate(
            id="USE-RECREATION-TOURISM-INFRA",
            engine="USE",
            name="Recreation / parks / tourism infrastructure use",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={
                "status": "PARTIAL",
                "state_2pct_tourism_tax_fy2026_usd": 26851526,
                "note": "Visitor engine overlap; already marketing-earmarked",
            },
            current_rate_or_structure="2% Parks & Tourism tax; park entry/permits; local hospitality",
            current_collections_usd=26851526,
            already_spent=True,
            already_spent_note="2% tax funds tourism marketing",
            legally_plausible_alternative="Destination fees / park premium permits — demand elasticity required",
            gross_revenue_note="~$27M — <0.4% of combined replacement target",
            collection_admin_cost="Existing",
            behavioral_response="Visitor suppression if excessive",
            local_community_share="Local hospitality taxes separate",
            state_share="2% tourism tax",
            volatility="Tourism cycle",
            stress_case="Demand suppression",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Generally applicable tourism/lodging taxes",
            bucket="NOT_MATERIAL_AS_REPLACEMENT_ENGINE",
            proportionality_or_depletion_test="Good visitor-use alignment; scale support-only",
        ),
    ]

    depletion_candidates = [
        candidate(
            id="DEPL-NATURAL-GAS-SEVERANCE",
            engine="DEPLETION",
            name="Natural gas severance tax (full collections, not GR line only)",
            income_form="TAX",
            addressable_base={
                "status": "BOUND",
                "gross_taxable_mcf_cy2025": MCF_CY2025,
                "fy2026_gross_severance_usd": NG_FY2026,
                "fy2025_usd": NG_FY2025,
                "fy2024_usd": NG_FY2024,
                "fy2023_usd": NG_FY2023,
                "source": "DFA monthlyGrossNGSFY26 / MCFbyPeriodNGS",
                "illustrative_market_value_at_3_usd_per_mcf": round(illustrative_mv_at_3),
                "illustrative_blended_effective_rate_vs_3_usd": round(blended_eff, 4) if blended_eff else None,
                "note": "Price $3/Mcf is ILLUSTRATIVE for sensitivity only — not a DFA bind",
            },
            current_rate_or_structure="1.25% / 1.5% / 5% of market value by well class (A.C.A. § 26-58-111)",
            current_collections_usd=NG_FY2026,
            already_spent=True,
            already_spent_note="~95% Highway Revenue Distribution special revenue; ~5% GR (~$1.28M of FY26). GR table $10.6M is NOT the full gas severance story.",
            legally_plausible_alternative={
                "rate_structure": "Raise preferential classes toward 5% or add permanent-fund surcharge on NEW production",
                "illustrative_5pct_of_mv_at_3_usd": round(illustrative_5pct),
                "illustrative_uplift_vs_fy26_if_mv_held_usd": round(max(0, illustrative_5pct - NG_FY2026)),
                "count_status": "NOT COUNTED — hypothetical; dedication still highway-dominated unless statute redesigns NEW increment to Prosperity Fund",
            },
            gross_revenue_note=f"FY2026 gross ${NG_FY2026:,}; highway portion ~${ng_hwy_portion:,}; GR portion ~${ng_gr_portion:,}",
            collection_admin_cost="EXISTING DFA system",
            behavioral_response="Drilling/production response to rate; high-cost well incentives matter",
            local_community_share="Indirect via highway aid; not a community permanent share today",
            state_share="~95% highways / ~5% GR under current allocation",
            volatility="VERY_HIGH — FY2023 $76.9M → FY2024 $16.4M",
            stress_case="Commodity price crash (observed); cannot underwrite IIT retirement",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Generally applicable severance; Commerce Clause OK if non-discriminatory; rededicating highway share has statutory/political constraints",
            bucket="NOT_MATERIAL_AS_REPLACEMENT_ENGINE",
            proportionality_or_depletion_test="Correct depletion instrument, wrong scale/stability/dedication for IIT replacement; support/highway engine",
            allocation_split_usd={"highway_special_approx": ng_hwy_portion, "gr_approx": ng_gr_portion},
        ),
        candidate(
            id="DEPL-OIL-SEVERANCE",
            engine="DEPLETION",
            name="Oil severance / oil revenues",
            income_form="TAX",
            addressable_base={
                "status": "BOUND_COLLECTIONS",
                "fy2026_gross_usd": OIL_FY2026,
                "fy2025_gross_usd": OIL_FY2025,
                "source": "DFA oilRevenueFY26 / FY25",
            },
            current_rate_or_structure="4–5% of market value + per-barrel assessments (A.C.A. § 26-58-111 et seq.)",
            current_collections_usd=OIL_FY2026,
            already_spent=True,
            already_spent_note="Distributed under oil severance statutes (GR + county aid pathways) — treat as committed",
            legally_plausible_alternative="Rate redesign / permanent-fund carve-out on incremental — UNMODELED",
            gross_revenue_note="~$12.2M FY2026 — small vs target",
            collection_admin_cost="EXISTING",
            behavioral_response="Production response",
            local_community_share="County aid share under statute",
            state_share="Remainder per statute",
            volatility="HIGH — oil price cycles",
            stress_case="Price crash",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Generally applicable severance",
            bucket="NOT_MATERIAL_AS_REPLACEMENT_ENGINE",
            proportionality_or_depletion_test="Legitimate depletion tax; not material for $7.23B",
        ),
        candidate(
            id="DEPL-BRINE-LITHIUM",
            engine="DEPLETION",
            name="Brine / lithium — severance + private royalty + permanent-fund share (design)",
            income_form=["TAX", "FEE_RENT_ROYALTY", "RETURN"],
            addressable_base={
                "status": "EMERGING_NOT_PRODUCING_AT_SCALE",
                "aoGC_royalty_rate_to_brine_owners_percent": 2.5,
                "brine_severance_usd_per_1000_barrels": 2.45,
                "additional_museum_levies_usd_per_1000_barrels": 0.30,
                "usgs_smackover_lithium_tons_range": [5000000, 19000000],
                "commercial_production_expected": "≈2028+",
                "note": "2.5% royalty is primarily to private brine rights owners — NOT automatic state public income",
            },
            current_rate_or_structure="Brine severance $2.45/1000 bbl; OGC 2.5% LCE royalty to owners; brine acreage fees (~$65/acre class)",
            current_collections_usd=0,
            already_spent=False,
            already_spent_note="No material commercial lithium public cash flow yet; future brine severance may be small vs private royalties",
            legally_plausible_alternative={
                "stack": [
                    "severance redesign",
                    "public-land / state-owned brine royalty",
                    "community impact payment",
                    "mandatory permanent-fund contribution from production",
                    "state equity/participation (Enterprise engine)",
                ],
                "private_royalty_illustrative_literature_usd_per_year_scale": "tens of millions to brine owners across projects — NOT state GR",
            },
            gross_revenue_note="State COUNTABLE public income still $0 until production + statutory statute/ownership path",
            collection_admin_cost="OGC/DFA systems emerging",
            behavioral_response="Royalty/severance levels affect project FID; race-to-bottom risk vs other jurisdictions",
            local_community_share="Critical design variable — many brine rights held by non-local owners",
            state_share="Currently weak relative to private royalties unless redesigned",
            volatility="HIGH — lithium price + project timing",
            stress_case="Delayed FID; price crash; leakage of royalties out of state",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Severance generally OK; public permanent-fund share needs statute; no export-discriminatory tax",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Best long-run Depletion opportunity — convert finite lithium into permanent Arkansas wealth; not countable until cash flows exist",
        ),
        candidate(
            id="DEPL-OTHER-MINERALS",
            engine="DEPLETION",
            name="Other minerals (default 5% FMV severance class)",
            income_form="TAX",
            addressable_base={"status": "NEE", "statute": "A.C.A. § 26-58-111(8) residual class"},
            current_rate_or_structure="Generally 5% of fair market value at severance for unspecified natural resources",
            current_collections_usd=None,
            already_spent=None,
            already_spent_note="Unknown split without DFA mineral breakout",
            legally_plausible_alternative="Commodity-specific royalty + permanent fund",
            gross_revenue_note="UNMODELED — likely not material vs gas/oil historically",
            collection_admin_cost="EXISTING residual",
            behavioral_response="NEE",
            local_community_share="NEE",
            state_share="NEE",
            volatility="Commodity",
            stress_case="NEE",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Generally applicable severance",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Needs production inventory before any claim",
        ),
        candidate(
            id="DEPL-TIMBER",
            engine="DEPLETION",
            name="Timber severance",
            income_form="TAX",
            addressable_base={
                "status": "RATE_BOUND_COLLECTIONS_NEE",
                "pine_usd_per_ton": 0.178,
                "other_usd_per_ton": 0.125,
                "statute": "A.C.A. § 26-58-111(7)",
            },
            current_rate_or_structure="Per-ton primary processor tax",
            current_collections_usd=None,
            already_spent=None,
            already_spent_note="Distribution NEE this slice — assume committed until proven otherwise",
            legally_plausible_alternative="Rate update + public-land stumpage/lease stack",
            gross_revenue_note="UNMODELED without tonnage series",
            collection_admin_cost="EXISTING",
            behavioral_response="Harvest timing",
            local_community_share="NEE",
            state_share="NEE",
            volatility="MODERATE",
            stress_case="Housing/lumber cycle",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Generally applicable",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Renewable vs finite debate; public-land lease returns may matter more than severance nickels",
        ),
        candidate(
            id="DEPL-PUBLIC-LAND-LEASES",
            engine="DEPLETION",
            name="Public land / resource leases & concessions",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={"status": "NEE", "note": "State parks, wildlife, land commission, school lands inventories needed"},
            current_rate_or_structure="Lease/concession contracts",
            current_collections_usd=None,
            already_spent=None,
            already_spent_note="Often dedicated to managing agencies",
            legally_plausible_alternative="Market-rate leases + Prosperity Fund carve-out on new concessions",
            gross_revenue_note="UNMODELED",
            collection_admin_cost="Contract admin",
            behavioral_response="Bidder competition",
            local_community_share="Site-specific",
            state_share="Agency/fund",
            volatility="Contract cycle",
            stress_case="Below-market legacy leases",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="Lease/property authority; gift-of-public-property constraints",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Strong FEE/RENT alignment; inventory-first",
        ),
        candidate(
            id="DEPL-INDUSTRIAL-WATER",
            engine="DEPLETION",
            name="Industrial-scale water withdrawal / consumptive use",
            income_form="FEE_RENT_ROYALTY",
            addressable_base={"status": "NEE", "note": "Critical for brine/lithium and large industry; no statewide fee series bound"},
            current_rate_or_structure="Limited statewide pricing of scarce water as public resource",
            current_collections_usd=None,
            already_spent=False,
            already_spent_note="No major statewide industrial water royalty bound",
            legally_plausible_alternative="Consumptive-use fee / aquifer impact payment with community + permanent-fund shares",
            gross_revenue_note="UNMODELED — legal/water-rights complexity high",
            collection_admin_cost="Would need metering/reporting regime",
            behavioral_response="Siting / recycling / out-of-state diversion",
            local_community_share="Should be first-order design variable",
            state_share="Design variable",
            volatility="Drought and industrial cycle",
            stress_case="Riparian/regulatory takings claims; competitiveness",
            incremental_recurring_usd_countable=0,
            constitutional_legal_status="LEGAL_PENDING — water rights regime careful",
            bucket="PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING",
            proportionality_or_depletion_test="Scarce-resource rent; not household water rates",
        ),
    ]

    countable = [c for c in use_candidates + depletion_candidates if c["bucket"] == "COUNTABLE_NOW"]
    plausible = [c for c in use_candidates + depletion_candidates if c["bucket"] == "PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING"]
    not_material = [c for c in use_candidates + depletion_candidates if c["bucket"] == "NOT_MATERIAL_AS_REPLACEMENT_ENGINE"]

    countable_sum = sum(c["incremental_recurring_usd_countable"] or 0 for c in use_candidates + depletion_candidates)

    out = {
        "version": "1.0.0",
        "slice_id": SLICE,
        "generated_at": "2026-08-12",
        "decision_id": DEC,
        "update_id": UPD,
        "hypothesis_id": "CC-HYP-PROSPERITY-BASED-REVENUE-REPLACEMENT-SYSTEM",
        "status": "CASHFLOW_PASS_ZERO_COUNTABLE",
        "questions": {
            "use": "What public-system use can Arkansas charge for without simply recreating a broad household tax?",
            "depletion": "What finite/scarce Arkansas assets are depleted/commercially exploited, and what recurring public income can be captured before value leaves?",
        },
        "count_rule": "Only final incremental_recurring_usd_countable may be considered against the ~$7.23B burden. Already-spent streams cannot be counted twice.",
        "replacement_target_usd": COMBINED_TARGET,
        "counted_toward_replacement_usd": countable_sum,
        "schema_fields": [
            "addressable_base",
            "current_rate_or_structure",
            "current_collections_usd",
            "already_spent",
            "legally_plausible_alternative",
            "gross_revenue",
            "collection_admin_cost",
            "behavioral_response",
            "local_community_share",
            "state_share",
            "volatility",
            "stress_case",
            "incremental_recurring_usd_countable",
            "constitutional_legal_status",
        ],
        "bound_scale_summary": {
            "motor_fuel_fy2026_usd": round(FUEL_FY2026),
            "natural_gas_severance_fy2026_usd": NG_FY2026,
            "natural_gas_severance_fy2023_peak_usd": NG_FY2023,
            "oil_revenue_fy2026_usd": OIL_FY2026,
            "dfa_gr_severance_line_fy2026_usd": GR_SEVERANCE_FY2026,
            "gr_line_vs_full_gas_note": "GR severance line ($10.6M) understates full gas severance (~$25.6M) because ~95% is highway special revenue",
            "tourism_2pct_fy2026_usd": 26851526,
        },
        "use_candidates": use_candidates,
        "depletion_candidates": depletion_candidates,
        "buckets": {
            "COUNTABLE_NOW": {
                "ids": [c["id"] for c in countable],
                "incremental_recurring_usd": countable_sum,
                "verdict": "EMPTY — no evidence-backed incremental, legally free, reserved cash flow cleared this pass",
            },
            "PLAUSIBLE_BUT_UNMODELED_LEGAL_PENDING": {
                "ids": [c["id"] for c in plausible],
                "verdict": "Heavy-vehicle ESAL fees; airport/port participation; lithium permanent-fund/public share; other minerals; timber; public-land leases; industrial water rents",
            },
            "NOT_MATERIAL_AS_REPLACEMENT_ENGINE": {
                "ids": [c["id"] for c in not_material],
                "verdict": "Motor fuel (~$572M) and gas/oil severance are real but already spent and/or too volatile/small to carry ~$7.23B; household water/waste and tiny EV fees unsuitable as replacement engines",
            },
        },
        "engine_role_verdict": {
            "USE": "SUPPORT ENGINE — large existing road-use base (~$0.57B) must stay with transportation; incremental replacement capacity not proven",
            "DEPLETION": "SUPPORT / FUTURE OPTION — full gas severance ~$26M (volatile; mostly highways); lithium could matter after 2028+ if public permanent share designed; not countable now",
            "where_larger_capacity_likely_lives": [
                "Human-capital",
                "Value Capture",
                "Enterprise",
                "Prosperity Fund",
                "External Income",
            ],
        },
        "holds": [
            "overall_percent_held_at_43",
            "KEEP_AS_HYPOTHESIS",
            "no_abolish_today",
            "zero_counted_until_cashflow_model",
            "already_spent_cannot_double_count",
            "no_discriminatory_export_tax",
        ],
    }

    path = OUT / "use_depletion_cashflow_ledger.json"
    path.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                "path": str(path),
                "countable_usd": countable_sum,
                "use_n": len(use_candidates),
                "depl_n": len(depletion_candidates),
                "buckets": {k: v["ids"] for k, v in out["buckets"].items()},
                "ng_fy26": NG_FY2026,
                "fuel_fy26": round(FUEL_FY2026),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
