#!/usr/bin/env python3
"""One-pass AFIC/shared-kitchen operating-statement & utilization bind.

Depth limit (Steve completion priority): ONE focused pass.
- If strong evidence appears: bind it.
- If not: record the gap and CLOSE the food-hub evidence stage.
No third/fourth/fifth food-hub investigation to manufacture precision.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "imports" / "arkansas-revenue-replacement"
OUT.mkdir(parents=True, exist_ok=True)

SLICE = "CC-ARKANSAS-FOOD-FACILITY-OPERATING-STATEMENT-AND-UTILIZATION-BIND-1.0"
DEC, UPD = "CC-DEC-148", "UPD-161"
DEMOTED_BASE_16Y = 836_986_729


def fee_schedule_bound() -> dict:
    return {
        "id": "FEE-AFIC-MCO-001",
        "facility": "AFIC@MCO (Arkansas Food Innovation Center at Market Center of the Ozarks)",
        "geography": "Springdale, AR — 821 E Emma Ave",
        "facility_scale": "~45,000 sq ft (reported)",
        "opened": "May 2025 (press)",
        "evidence_quality": "PUBLISHED_FEE_SCHEDULE_BOUND",
        "shared_use_kitchen_hourly_usd": {
            "lt_5_employees": {"cooking_station": 15, "non_cooking_station": 9},
            "gt_5_employees": {"cooking_station": 25, "non_cooking_station": 15},
        },
        "food_truck_monthly_usd": {"tier_1": 75, "tier_2_with_overnight_parking": 100},
        "storage_cage_monthly_usd": {"dry": 46, "refrigerated": 69, "frozen": 69},
        "other_fees_usd": {
            "delivery_signing_add_on_monthly": 50,
            "conference_room_hourly": 50,
            "conference_room_with_bakeshop_hourly": 70,
            "popup_10x10_per_event": 25,
        },
        "related_afic_fayetteville_lab_fees_note": "Separate AFIC (Fayetteville) publishes lab/process-authority fees (e.g. pH $20, Aw $30, process authority letter $200) — not AFIC@MCO P&L",
        "sources": [
            "https://aficmco.uada.edu/commissary-kitchen/",
            "https://www.nwaonline.com/news/2025/oct/29/center-in-springdale-fosters-food-entrepreneurs/",
            "https://afic.uada.edu/services/",
        ],
    }


def utilization_and_pnl_gap() -> dict:
    return {
        "status": "EVIDENCE_GAP_RECORDED_ONE_PASS_COMPLETE",
        "searched_for": [
            "facility operating statement / P&L",
            "annual or monthly utilization hours",
            "throughput / batch / contract-processing volumes",
            "O&M, utilities, labor, debt service",
            "net cash after reinvestment/reserves",
        ],
        "found": "Fee schedule and facility description only",
        "not_found": [
            "published operating statement for AFIC@MCO",
            "utilization rate or booked hours series",
            "revenue totals from kitchen/storage/contract processing",
            "free/distributable cash",
        ],
        "uada_open_checkbook_note": (
            "UADA Open Checkbook provides Division expenditure transparency but is unaudited/raw "
            "and not an AFIC@MCO facility P&L — does not clear free-cash reconstruction."
        ),
        "open_checkbook_url": "https://www.uada.edu/about/open_checkbook.aspx",
        "implication": (
            "Fees prove a public/shared facility can charge for access. Fees without utilization "
            "and cost structure cannot produce COUNTABLE reserved public cash."
        ),
    }


def stage_closure() -> dict:
    return {
        "food_hub_evidence_stage": "CLOSED_FIRST_PASS_MATURITY",
        "book_architecture_posture": (
            "Arkansas produces enormous agricultural value, but currently available evidence does "
            "not establish the distributable cash generated by the proposed ownership model. "
            "Therefore, the model identifies food processing and value retention as a "
            "high-potential fiscal pathway while refusing to count speculative revenue. "
            "Facility-level validation becomes an implementation-stage requirement."
        ),
        "remaining_validation": "IMPLEMENTATION_STAGE_GATE — not another research branch now",
        "do_not": [
            "third_food_hub_investigation",
            "fourth_food_hub_investigation",
            "manufacture_precision_without_evidence",
            "count_fee_schedules_as_reserved_cash",
        ],
        "completion_priority": {
            "objective": "BUILD THE COMPLETE SYSTEM → FINISH THE BOOK → identify gaps → stress-test → refine → implementation-grade validation",
            "rejects": "perfect one module → perfect another → discover three more questions → never finish",
            "push_against": [
                "unnecessary_new_branches",
                "research_beyond_what_current_chapter_needs",
                "attempts_to_perfect_something_already_sufficient_for_master_build",
            ],
            "unresolved_questions_become": [
                "validation_requirements",
                "appendices",
                "implementation_gates",
                "second_pass_research",
            ],
        },
    }


def build() -> dict:
    fees = fee_schedule_bound()
    gap = utilization_and_pnl_gap()
    closure = stage_closure()

    ledger = {
        "version": "1.0.0",
        "slice_id": SLICE,
        "generated_at": "2026-08-15",
        "decision_id": DEC,
        "update_id": UPD,
        "hypothesis_id": "CC-HYP-PROSPERITY-BASED-REVENUE-REPLACEMENT-SYSTEM",
        "incubator_alias": "HYP-131",
        "engine_id": "ENGINE-EXTERNAL-INCOME",
        "status": "ONE_PASS_COMPLETE_STAGE_CLOSED_ZERO_COUNTABLE",
        "depth_limit": "ONE_FOCUSED_PASS — bind if strong; else record gap and move on",
        "central_question": (
            "Can Arkansas bind AFIC@MCO / shared-kitchen operating statements, utilization, "
            "and fees in one focused pass — and if not, close the food-hub evidence stage at "
            "first-pass maturity without further drilling?"
        ),
        "fee_schedule": fees,
        "utilization_and_operating_statement": gap,
        "illustrative_revenue_note": {
            "status": "NOT_MODELED_AS_COUNTABLE",
            "rule": "Hourly fees × unknown hours = speculation. Do not invent utilization.",
        },
        "stage_closure": closure,
        "prior_food_hub_chain": [
            "CC-ARKANSAS-FOOD-HUB-OWNERSHIP-AND-PROCESSING-MARGIN-BIND-1.0",
            "CC-ARKANSAS-FOOD-HUB-AND-PROCESSING-FACILITY-CASHFLOW-CASE-BIND-1.0",
            SLICE,
        ],
        "countable_now_usd": 0,
        "promoted_to_countable": [],
        "replacement_stack_feed": {
            "dollars_added_to_countable": 0,
            "demoted_base_16y_ceiling_unchanged_usd": DEMOTED_BASE_16Y,
            "rule": "Fee schedules are not reserved public cash",
        },
        "headline": {
            "fees_bound": True,
            "utilization_bound": False,
            "operating_statement_bound": False,
            "countable_usd": 0,
            "reading": (
                "One-pass complete. AFIC@MCO fee schedule bound; utilization and P&L remain gaps. "
                "Food-hub evidence stage closed at first-pass maturity. Facility validation is an "
                "implementation gate. COUNTABLE $0. Advance the master build."
            ),
        },
        "next_slice": "CC-PHASE-2.1-BASELINE-DEFINITION-LOCKS-AND-NEXT-LEGITIMATE-FILLS-1.0",
        "research_next_non_food_hub": [
            "CC-PHASE-2.1-BASELINE-DEFINITION-LOCKS-AND-NEXT-LEGITIMATE-FILLS-1.0",
            "CC-ARKANSAS-AEDC-INCENTIVE-EQUITY-CONVERSION-LEGAL-MEMO-1.0",
        ],
        "food_hub_second_pass": "GATED_IMPLEMENTATION_STAGE_ONLY",
        "holds": [
            "overall_percent_held_at_43",
            "KEEP_AS_HYPOTHESIS",
            "completion_first_discipline",
            "food_hub_stage_closed_first_pass",
            "fee_schedule_ne_reserved_cash",
            "no_further_food_hub_drilling_now",
            "hyp134_quarantined_from_countable",
            "fewer_new_architectures_more_evidence",
        ],
    }

    path = OUT / "food_facility_operating_statement_utilization_ledger.json"
    path.write_text(json.dumps(ledger, indent=2) + "\n", encoding="utf-8")
    return {
        "path": str(path),
        "countable_now": 0,
        "fees_bound": True,
        "utilization_bound": False,
        "stage": "CLOSED_FIRST_PASS_MATURITY",
    }


if __name__ == "__main__":
    print(json.dumps(build()))
